import type { Category, Suggestion } from "./types";

export const CATEGORIES: Category[] = [
  { id: "relationships", label: "Relationships", values: ["Love", "Family", "Partnership", "Friendship", "Parenting"] },
  { id: "health", label: "Health", values: ["Physical Health", "Mental Wellbeing", "Sleep", "Fitness", "Self-Care"] },
  { id: "growth", label: "Growth", values: ["Learning", "Curiosity", "Personal Development", "Creativity"] },
  { id: "career", label: "Career", values: ["Career", "Achievement", "Responsibility", "Leadership"] },
  { id: "community", label: "Community", values: ["Helping Others", "Volunteering", "Citizenship", "Environment"] },
  { id: "spirituality", label: "Spirituality", values: ["Faith", "Spiritual Growth", "Mindfulness"] },
  { id: "leisure", label: "Leisure", values: ["Fun", "Adventure", "Recreation", "Playfulness"] },
  { id: "character", label: "Character", values: ["Compassion", "Honesty", "Courage", "Gratitude", "Kindness"] },
];

export const VALUE_CATEGORY: Record<string, string> = {};
CATEGORIES.forEach((c) => c.values.forEach((v) => (VALUE_CATEGORY[v] = c.label)));

export const CAT_ICON: Record<string, string> = {
  Relationships: "heart",
  Health: "bolt",
  Growth: "spark",
  Career: "chart",
  Community: "leaf",
  Spirituality: "leaf",
  Leisure: "spark",
  Character: "shield",
};

export function valueIcon(value: string): string {
  const cat = VALUE_CATEGORY[value];
  return CAT_ICON[cat] || "heart";
}

const ACTIVITIES: Record<string, Record<string, string[]>> = {
  Love: {
    "5-low": ["Send a voice note telling someone you love them", "Reread a sweet old message from a partner or friend", "Write 3 things you love about your partner"],
    "5-medium": ["Leave a sticky note with a loving message somewhere they'll find it", "Send a photo that reminded you of them", "Text someone 'I was thinking of you'"],
    "5-high": ["Surprise them with a small spontaneous gesture", "Plan a mini date idea to propose", "Write a heartfelt compliment and deliver it in person"],
    "10-low": ["Look through old photos together or alone", "Write a short letter you don't have to send", "Listen to a song that reminds you of someone you love"],
    "10-medium": ["Have a 10-min check-in call with someone you care about", "Write a list of your favourite shared memories", "Make them a cup of tea or coffee just because"],
    "10-high": ["Cook or prepare something small for someone you love", "Plan a surprise for this week", "Write and send a proper heartfelt message"],
    "20-low": ["Watch a favourite short video or show clip together", "Journal about what love means to you right now", "Browse through a shared photo album"],
    "20-medium": ["Take a walk together with no agenda", "Cook a simple meal together", "Have a real conversation — no phones"],
    "20-high": ["Plan a date night in detail", "Write a long love letter", "Create a playlist for someone special"],
    "45-low": ["Watch a comforting film together", "Do a slow puzzle or activity side by side", "Read in the same room"],
    "45-medium": ["Cook a full meal together", "Go for a long walk and talk", "Do a creative activity together — drawing, scrapbooking"],
    "45-high": ["Plan a trip or weekend away together", "Have a deep relationship check-in conversation", "Create something meaningful for them — art, a video, a photo book"],
  },
  Family: {
    "5-low": ["Send a family group chat message", "Call a relative just to say hello", "Look at a family photo and reflect on a good memory"],
    "5-medium": ["Text a sibling or parent something you appreciate about them", "Share a funny memory in the family chat", "Suggest a future family plan via message"],
    "5-high": ["Organise a quick family catch-up call", "Send a voice message to a distant relative", "Write a short note to a family member you haven't spoken to in a while"],
    "10-low": ["Call a grandparent or older relative", "Browse old family photos", "Journal about a favourite family memory"],
    "10-medium": ["Have a 10-min check-in with a parent or sibling", "Play a quick card or word game with whoever is home", "Help a family member with something small"],
    "10-high": ["Organise a family movie night for this week", "Do a small act of service for a family member", "Write down a family tradition you want to keep or start"],
    "20-low": ["Watch a home video or slideshow", "Call a family member you haven't spoken to in months", "Rest together — read in the same space"],
    "20-medium": ["Cook a family recipe together", "Take a walk with a family member", "Share stories from childhood over tea"],
    "20-high": ["Start a family scrapbook or photo project", "Plan a family gathering or celebration", "Teach a skill to a younger family member"],
    "45-low": ["Watch a film that has family meaning", "Do a slow shared activity — puzzle, cards", "Rest and be present together"],
    "45-medium": ["Cook and eat a meal together", "Visit a relative", "Go to a local market or place you all enjoy"],
    "45-high": ["Plan a family day out", "Start a family tradition — games night, Sunday ritual", "Create a family memory box or album together"],
  },
  Partnership: {
    "5-low": ["Send a loving or funny message to your partner", "Reread a meaningful conversation", "Sit quietly together without screens"],
    "5-medium": ["Ask your partner one genuine question about their day", "Leave a note somewhere they'll find it", "Send them a song you've been listening to"],
    "5-high": ["Plan a date or surprise for this week", "Tell them one specific thing you appreciate about them", "Make a small gesture — their favourite snack, a hug"],
    "10-low": ["Have a slow cup of tea together with no agenda", "Journal about what's going well in your relationship", "Sit and listen to music together"],
    "10-medium": ["Have a 10-min undistracted conversation", "Take a short walk together", "Do a quick check-in: how are we both feeling this week?"],
    "10-high": ["Plan something you've both been putting off", "Write down what you love about your relationship right now", "Do something active together — stretch, short workout"],
    "20-low": ["Watch something you both enjoy", "Do a quiet activity in the same space", "Talk about something lighthearted — no stress topics"],
    "20-medium": ["Cook a meal together", "Go for a walk and talk about something you're each excited about", "Do a fun activity — trivia, card game, sketching"],
    "20-high": ["Have a relationship check-in — what's working, what needs attention", "Plan a future trip or goal together", "Do an active activity — bike ride, dance, sport"],
    "45-low": ["Watch a film or series episode together", "Rest together — reading, napping nearby", "Do a slow shared activity"],
    "45-medium": ["Cook a full meal and eat slowly together", "Explore a local neighbourhood together", "Play a board game or creative game"],
    "45-high": ["Go on a proper date — outside the home", "Start a shared project or hobby", "Have a deep values conversation about where you both want to go"],
  },
  Friendship: {
    "5-low": ["Send a meme or video to a friend who would love it", "Reply to a friend's story with something genuine", "Think of one friend and write down why they matter to you"],
    "5-medium": ["Text a friend you haven't spoken to in a while", "Send a voice note instead of a text", "Share something you found interesting with a friend"],
    "5-high": ["Suggest a plan with a friend this week", "Send a friend a specific compliment", "Make a list of 3 friends you want to see more of"],
    "10-low": ["Call a friend just to hear their voice", "Look through old photos from time spent together", "Write a message you've been meaning to send"],
    "10-medium": ["Have a quick catch-up call", "Share something you've been reading, watching, or thinking about", "Play an online game together briefly"],
    "10-high": ["Plan a friend date and send the invite", "Do a shared workout or walk over a call", "Start a shared playlist or watch list"],
    "20-low": ["Watch the same thing on separate screens and text during", "Have a low-key video call", "Journal about what you value in your closest friendships"],
    "20-medium": ["Go for a walk and call a friend", "Meet for a coffee", "Do a shared creative activity over video"],
    "20-high": ["Plan a group activity for the coming weeks", "Go for a run or active walk together", "Start something together — a challenge, a project, a book club"],
    "45-low": ["Watch a film and video-call before and after", "Have a long slow catch-up call", "Cook something and eat over video chat"],
    "45-medium": ["Meet a friend for coffee or a walk", "Explore somewhere new together", "Cook together at each other's homes"],
    "45-high": ["Plan and go on a day out", "Do an activity you've both been wanting to try", "Have a proper dinner together — cook or go out"],
  },
  Parenting: {
    "5-low": ["Sit beside your child while they play — no phone", "Tell them one specific thing you're proud of them for", "Read one short picture book page by page"],
    "5-medium": ["Play a quick silly game — 20 questions, I spy", "Ask them about their favourite part of the day", "Do a small craft or drawing together"],
    "5-high": ["Take them outside for a quick run around", "Do a 5-min dance session", "Start a fun challenge — who can balance longest"],
    "10-low": ["Read a story together", "Do a quiet activity — colouring, puzzles", "Lie down and make up a story verbally"],
    "10-medium": ["Do a short baking activity — simple recipe", "Play a board or card game", "Do a short nature walk and spot things together"],
    "10-high": ["Do a physical game — obstacle course, tag", "Teach them a simple skill — tie a knot, fold origami", "Do a science experiment from things in the kitchen"],
    "20-low": ["Watch a short film or show together", "Do a quiet craft activity", "Have a slow breakfast or snack together"],
    "20-medium": ["Bake something simple together", "Go to the park", "Do a creative project — draw a comic, build something"],
    "20-high": ["Go for a bike ride or active outdoor game", "Do a longer craft or building project", "Cook a full meal together, age-appropriately"],
    "45-low": ["Watch a film together", "Do a long puzzle or quiet building activity", "Have a slow, no-agenda afternoon together"],
    "45-medium": ["Go on a nature walk or explore somewhere local", "Do a bigger creative project", "Cook a full meal together"],
    "45-high": ["Go to a playground, park, or sports activity", "Start a longer project they're excited about", "Plan and do a mini adventure together"],
  },
  "Physical Health": {
    "5-low": ["Do 5 minutes of gentle stretching in bed or on the floor", "Take 3 slow deep breaths and do neck rolls", "Walk slowly to get some water and stand for a moment"],
    "5-medium": ["Do 5 minutes of bodyweight movement — squats, lunges, pushups", "Take a brisk 5-min walk outside or around the building", "Do a quick mobility routine for hips and back"],
    "5-high": ["Do a 5-min HIIT circuit — jumping jacks, burpees, mountain climbers", "Sprint up and down stairs for 5 minutes", "Do a fast jump rope or skipping session"],
    "10-low": ["Do a full gentle stretch routine — floor-based", "Take a slow 10-min walk and focus on breathing", "Do a seated yoga or mobility flow"],
    "10-medium": ["Go for a brisk 10-min walk", "Do a 10-min bodyweight circuit", "Stretch dynamically — leg swings, arm circles, hip opens"],
    "10-high": ["Run for 10 minutes at a pushing pace", "Do a 10-min HIIT workout", "Go for a fast bike ride"],
    "20-low": ["Do a 20-min yin yoga or restorative stretch session", "Take a slow walk in nature", "Do a gentle swim"],
    "20-medium": ["Go for a 20-min run or brisk walk", "Do a full bodyweight workout", "Swim or cycle at a moderate pace"],
    "20-high": ["Do a 20-min intense run or interval training", "Do a challenging gym circuit", "Go for a hard bike ride or row"],
    "45-low": ["Do a full yoga class (online)", "Take a long slow walk", "Go for a gentle swim or aqua session"],
    "45-medium": ["Go to the gym and do a structured workout", "Go for a 45-min run or walk-run", "Do a sport — tennis, football, basketball with friends"],
    "45-high": ["Do a full training session — weights, cardio, sport", "Go for a long hard run", "Attend a fitness class — HIIT, spin, boxing"],
  },
  "Mental Wellbeing": {
    "5-low": ["Write 3 things that are okay right now", "Do a 5-min breathing exercise — box breathing or 4-7-8", "Sit quietly and notice 5 things around you (grounding)"],
    "5-medium": ["Journal for 5 minutes with no agenda — just write", "Step outside and walk slowly for 5 minutes", "Listen to one calming or uplifting song"],
    "5-high": ["Write a quick brain dump — everything on your mind, no filter", "Do a fast physical release — shake your body, jump, move", "Call or text someone who makes you feel good"],
    "10-low": ["Do a 10-min guided meditation", "Write a short letter to yourself — kind and honest", "Lie down and do a body scan"],
    "10-medium": ["Journal about what's been draining you and one thing that could shift it", "Go for a 10-min walk with no phone", "Do a 10-min guided breathing or mindfulness session"],
    "10-high": ["Do a 10-min journaling sprint — fears, hopes, what you need", "Exercise briefly as an emotional release", "Write down 3 things you're avoiding and pick one small step"],
    "20-low": ["Watch or read something comforting", "Do a longer meditation or breathing practice", "Rest without guilt — lie down and let your mind wander"],
    "20-medium": ["Journal deeply — what's going well, what's hard, what you need", "Go for a 20-min walk with no podcast — just thoughts", "Do a creative activity that requires no outcome"],
    "20-high": ["Write a longer journal entry about a difficult emotion or situation", "Talk to a friend about how you're really doing", "Start a self-understanding exercise — values, needs, patterns"],
    "45-low": ["Watch a documentary or film that moves you", "Do a full yoga or stretch session", "Rest intentionally — nap, read, be still"],
    "45-medium": ["Spend time in nature with no agenda", "Do a full journaling session — past, present, future", "Have an honest conversation with someone you trust"],
    "45-high": ["Go for a long run or workout as emotional processing", "Do a deep creative session — write, draw, make", "Spend focused time on something that makes you feel capable and alive"],
  },
  Sleep: {
    "5-low": ["Do a 5-min progressive muscle relaxation before bed", "Write tomorrow's top 3 priorities to clear your mind", "Dim your lights and put your phone in another room"],
    "5-medium": ["Do 5 minutes of gentle stretching before bed", "Write a brief brain dump to offload thoughts", "Set a consistent wake time and put it in your alarm now"],
    "5-high": ["Do 5 min of breathwork to wind down from a busy day", "Write out everything on your mind before sleep", "Plan tomorrow briefly so your brain can let go tonight"],
    "10-low": ["Do a 10-min guided sleep meditation", "Read something light and non-stimulating for 10 minutes", "Do gentle yoga or floor stretches in dim light"],
    "10-medium": ["Create a consistent wind-down routine and write it down", "Do a 10-min slow walk after dinner", "Journal about the day — let it close properly"],
    "10-high": ["Audit your sleep habits — bedtime, screen time, caffeine — and make one change", "Do a 10-min workout earlier in the day to improve tonight's sleep", "Prepare your bedroom: dark, cool, tidy, phone out"],
    "20-low": ["Take a warm bath or shower before bed", "Do a 20-min yin yoga or restorative session", "Read a book or listen to a calming podcast or audio"],
    "20-medium": ["Create a full bedtime routine and practise it tonight", "Go for an evening walk without screens", "Journal reflectively — what happened, how you feel, what you need tomorrow"],
    "20-high": ["Do a physical workout earlier in the day (this session) to improve sleep quality", "Redesign your sleep environment — blackout, white noise, temperature", "Track your sleep for a week — note patterns"],
    "45-low": ["Have a slow, screen-free evening — bath, book, tea", "Do a full restorative yoga or stretching session", "Listen to a sleep meditation or relaxation audio"],
    "45-medium": ["Create a full sleep protocol: timing, environment, pre-bed routine", "Go for a long evening walk", "Cook a light dinner, eat early, and wind down slowly"],
    "45-high": ["Exercise earlier in the day to regulate your sleep cycle", "Design a full digital sunset — no screens 1hr before bed, implemented tonight", "Research and implement one evidence-based sleep improvement"],
  },
  Fitness: {
    "5-low": ["Do 10 slow bodyweight squats and stretch after", "Do a 5-min foam rolling or self-massage session", "Walk briskly for 5 minutes"],
    "5-medium": ["Do a quick 5-min circuit — 3 exercises, no rest", "Do 5 minutes of jump rope or jumping jacks", "Do a short sprint interval — 30s on, 30s off, x5"],
    "5-high": ["Do a 5-min max-effort bodyweight blast", "Sprint for 5 minutes with full effort", "Do a kettlebell or dumbbell quick circuit"],
    "10-low": ["Do a full mobility routine — hips, spine, shoulders", "Walk for 10 minutes at a steady pace", "Do a 10-min gentle yoga flow focused on muscles you use most"],
    "10-medium": ["Do a 10-min full-body circuit — push, pull, legs, core", "Go for a 10-min run", "Do 10 minutes on a cardio machine at moderate pace"],
    "10-high": ["Do a 10-min AMRAP — as many rounds as possible of 3-4 exercises", "Run hard for 10 minutes with no stopping", "Do a 10-min kettlebell complex"],
    "20-low": ["Do a 20-min yoga or mobility session focused on recovery", "Walk for 20 minutes", "Foam roll and stretch all major muscle groups"],
    "20-medium": ["Do a 20-min structured workout — upper or lower body focus", "Go for a 20-min run at conversational pace", "Swim or cycle for 20 minutes"],
    "20-high": ["Do a 20-min intense circuit — strength + cardio combo", "Run with intervals for 20 minutes", "Do a challenging climbing, rowing, or sport session"],
    "45-low": ["Do a full yoga or pilates class", "Take a long walk", "Do a recovery session — stretching, light movement, foam rolling"],
    "45-medium": ["Do a full structured gym or home workout", "Go for a 45-min run", "Do a sport or group fitness class"],
    "45-high": ["Do a full challenging strength or sport training session", "Run a longer distance at race effort", "Attend a high-intensity class — CrossFit, HIIT, martial arts"],
  },
  "Self-Care": {
    "5-low": ["Make yourself a hot drink and drink it slowly — no phone", "Moisturise your face or hands with intention", "Close your eyes and take 5 slow breaths"],
    "5-medium": ["Do a 5-min skincare routine", "Step outside and get some daylight for 5 minutes", "Write one kind thing about yourself"],
    "5-high": ["Do a quick energising cold splash or shower", "Tidy one small corner that's been bothering you", "Move your body for 5 minutes in whatever way feels good"],
    "10-low": ["Do a face mask and lie down", "Make a nourishing snack and eat it slowly", "Read something enjoyable with no purpose"],
    "10-medium": ["Take a proper shower with intention — not rushed", "Do a 10-min stretch or yoga flow", "Write in a gratitude journal"],
    "10-high": ["Do a 10-min workout that feels good for your body", "Tidy and reset your physical space", "Plan one thing this week that is just for you"],
    "20-low": ["Have a long bath with a book or music", "Do a nourishing skincare or self-care ritual", "Rest properly — no phone, just quiet"],
    "20-medium": ["Cook yourself a proper nourishing meal", "Go for a walk with no agenda", "Do a full grooming or beauty ritual that you enjoy"],
    "20-high": ["Do a workout that leaves you feeling strong", "Declutter and reset your living space", "Plan your week with a focus on your own needs first"],
    "45-low": ["Have a long bath and afternoon of rest", "Watch or read something purely for pleasure", "Do a full slow self-care afternoon — everything that makes you feel cared for"],
    "45-medium": ["Go to a spa, sauna, or pool", "Cook a beautiful meal for yourself", "Spend time outdoors doing something gentle"],
    "45-high": ["Do a full workout + shower + grooming ritual", "Deep clean and reset your home environment", "Plan and prepare a week of nourishment — meals, movement, rest"],
  },
  Learning: {
    "5-low": ["Read one article on a topic you're curious about", "Watch a 5-min educational video", "Look up one thing you've always wondered about"],
    "5-medium": ["Do 5 minutes of a language app — Duolingo, Babbel", "Read one page of a non-fiction book", "Listen to 5 minutes of a podcast on a new topic"],
    "5-high": ["Write down 3 things you want to learn this month", "Take a short quiz or challenge on something you're studying", "Flashcard review — 5 minutes on anything you're learning"],
    "10-low": ["Read 10 minutes of a book", "Watch the intro of a documentary on a new topic", "Listen to a short educational podcast episode"],
    "10-medium": ["Write a short summary of something you learned this week", "Do a 10-min lesson on an app or course", "Have a conversation with someone about a topic you're curious about"],
    "10-high": ["Take notes on a topic you want to understand better", "Do a focused practice session — an instrument, language, skill", "Research one topic in depth with notes"],
    "20-low": ["Read a chapter of a book", "Watch an educational documentary segment", "Listen to a full short podcast episode"],
    "20-medium": ["Do a 20-min online course lesson", "Practice a skill deliberately — music, language, coding", "Write about something you're learning to consolidate it"],
    "20-high": ["Study a difficult topic for 20 minutes with focus", "Practice a skill with feedback — record yourself, test yourself", "Start a new learning project and plan the first steps"],
    "45-low": ["Watch a documentary or lecture", "Read for a long stretch", "Listen to a long-form educational podcast"],
    "45-medium": ["Do a full course lesson or series", "Have a learning conversation with someone more experienced", "Read and take notes for 45 minutes"],
    "45-high": ["Do a deep study session with active recall", "Practice a skill intensely — deliberate, focused, uncomfortable", "Start and structure a new learning goal for the coming month"],
  },
  Curiosity: {
    "5-low": ["Look up the origin of one word you use every day", "Read about one historical event you know nothing about", "Watch a 5-min 'how it's made' or explainer video"],
    "5-medium": ["Open a random Wikipedia article and follow one link", "Ask a curious question to someone around you", "Look up a topic that appeared in conversation this week"],
    "5-high": ["Write down 10 questions about something you don't understand", "Find an opposing view to something you believe and read it", "Go down a rabbit hole — set a 5-min timer and explore"],
    "10-low": ["Watch an interesting short documentary clip", "Read about an unfamiliar culture, place, or person", "Browse a museum or gallery online"],
    "10-medium": ["Listen to an episode of a new podcast genre you don't usually listen to", "Read the Wikipedia page of something obscure you've always wondered about", "Ask someone about their job, hobby, or expertise — just to learn"],
    "10-high": ["Research a topic you've been curious about and take notes", "Write a short paragraph about something new you learned today", "Find two opposing arguments on a topic and compare them"],
    "20-low": ["Watch a documentary on a topic outside your usual interests", "Browse a virtual museum or exhibition", "Read an essay on something unfamiliar"],
    "20-medium": ["Do a deep-dive on one topic — tabs, notes, ideas", "Listen to a long-form interview with someone you find interesting", "Explore a new discipline — philosophy, science, art history"],
    "20-high": ["Read and write: find a complex topic, read actively, take notes", "Explore a new creative medium as a beginner", "Do a research sprint on something you want to understand fully"],
    "45-low": ["Watch a long documentary on a topic you know nothing about", "Browse an online archive — art, science, history", "Read a long essay or longform article"],
    "45-medium": ["Deep-dive into a topic and produce a summary for yourself", "Visit a museum, exhibition, or library in person", "Start a curiosity journal — one new thing per day"],
    "45-high": ["Spend 45 minutes exploring a topic with depth and rigour", "Have a long conversation with an expert or knowledgeable friend", "Start learning an entirely new subject from scratch"],
  },
  "Personal Development": {
    "5-low": ["Read one quote or insight that challenges you", "Reflect on one thing you'd do differently this week", "Write down one thing you want to be better at"],
    "5-medium": ["Journal for 5 minutes on a personal pattern you want to change", "Listen to 5 minutes of a self-development podcast", "Read one page of a self-help or psychology book"],
    "5-high": ["Write your top 3 values and whether you're living them", "Identify one habit you want to build and write the first step", "Make one decision you've been avoiding"],
    "10-low": ["Read a chapter of a personal growth book", "Reflect on a recent challenge and what it taught you", "Listen to a short podcast on a mindset topic"],
    "10-medium": ["Do a 10-min journaling session on your biggest current goal", "Research one skill you want to develop", "Identify one belief that might be holding you back and examine it"],
    "10-high": ["Write a personal mission statement draft", "Design a daily routine that reflects your goals", "Make a list of your strengths and how you're using them"],
    "20-low": ["Read and reflect on a personal development chapter", "Watch a talk or interview on growth and motivation", "Journal freely about who you want to become"],
    "20-medium": ["Do a values audit — what matters most, is your life reflecting it", "Write a short-term goal with specific steps", "Listen to a long podcast episode on something you want to change"],
    "20-high": ["Do a full personal review — what's working, what isn't", "Design a 30-day challenge for yourself", "Write and commit to one concrete behaviour change"],
    "45-low": ["Read a significant portion of a personal development book", "Watch a documentary or lecture on human behaviour or potential", "Journal deeply about your life direction"],
    "45-medium": ["Do a full life audit across all areas", "Design your ideal week on paper", "Have a coaching-style conversation with someone you trust"],
    "45-high": ["Write a detailed personal development plan — 3 months out", "Start a new habit system with full tracking setup", "Attend a workshop, seminar, or structured personal growth session"],
  },
  Creativity: {
    "5-low": ["Doodle freely with no goal for 5 minutes", "Write 3 lines of a poem or song — don't overthink it", "Take one creative photo on your phone"],
    "5-medium": ["Write the first paragraph of a story with no plan", "Do a quick colour or design experiment", "Brainstorm 10 ideas on any topic — quantity over quality"],
    "5-high": ["Do a 5-min creative sprint — write, draw, make something fast", "Take 10 photos with an interesting constraint — one colour, reflections, textures", "Write the fastest short story you can in 5 minutes"],
    "10-low": ["Sketch something from observation — anything around you", "Free-write for 10 minutes with no editing", "Listen to a piece of music and write what it makes you see"],
    "10-medium": ["Start a small creative project — first page, first sketch, first note", "Try a creative exercise from a book or prompt generator", "Redesign something you use every day — sketch a better version"],
    "10-high": ["Write a short story with a beginning, middle, and end", "Create a design concept for something fictional", "Do a rapid creative challenge — 10 sketches in 10 minutes"],
    "20-low": ["Work on an ongoing creative project slowly", "Draw, paint, or collage with no outcome in mind", "Listen to an album and let it inspire free writing"],
    "20-medium": ["Write a full short piece — poem, essay, scene", "Do a 20-min design, illustration, or photography session", "Try a new creative medium for the first time"],
    "20-high": ["Do a focused creative work session on something you want to make", "Create a full concept — from idea to rough execution", "Produce something and share it — even a draft"],
    "45-low": ["Work slowly on a creative project you love", "Watch a documentary on an artist or maker you admire", "Create without pressure — just play"],
    "45-medium": ["Do a full creative session on one project", "Explore a new creative technique or tool", "Attend an art, music, or creative class"],
    "45-high": ["Complete a creative piece — start and finish something", "Do an intensive creative session with a self-imposed challenge", "Collaborate creatively with someone else"],
  },
  Career: {
    "5-low": ["Read one article relevant to your industry", "Look at one job posting that excites you even if you're not applying", "Write one thing that went well at work this week"],
    "5-medium": ["Update one section of your CV or portfolio", "Connect with one person on LinkedIn with a personalised note", "Write down your top career goal for this year"],
    "5-high": ["Reach out to someone in a role you aspire to", "Pitch or propose one idea at work today", "Identify one skill gap and find a resource to start filling it"],
    "10-low": ["Read an industry newsletter or blog post", "Listen to a work-relevant podcast for 10 minutes", "Journal about what energises you at work and what drains you"],
    "10-medium": ["Write a clear career goal with a 3-month milestone", "Research one company, role, or path you're curious about", "Do a skills audit — what do you have, what do you need"],
    "10-high": ["Write a professional bio or LinkedIn summary refresh", "Reach out to 2 people in your network with genuine intention", "Identify your next career step and write 3 actions to get there"],
    "20-low": ["Read a chapter of a career or professional development book", "Listen to a podcast interview with someone in your field", "Reflect and journal on where you want to be in 2 years"],
    "20-medium": ["Work on your portfolio or CV for 20 focused minutes", "Do an informational research session on a career transition", "Write a cover letter draft or professional communication"],
    "20-high": ["Apply for a role, opportunity, or programme you've been considering", "Do a deep skills session — practice a work-relevant skill", "Have a career conversation with a mentor or trusted colleague"],
    "45-low": ["Read a career or leadership book for a sustained period", "Watch a talk or interview with a leader you admire", "Journal and reflect on your career arc and direction"],
    "45-medium": ["Do a full portfolio or CV overhaul session", "Research and map out a full career transition plan", "Attend a professional development webinar or event"],
    "45-high": ["Do a focused skill-building session — coding, design, writing, speaking", "Build or present something that demonstrates your expertise", "Invest in a course, workshop, or programme relevant to your goals"],
  },
  Achievement: {
    "5-low": ["Write down one thing you've accomplished this week — even small", "Look at a list of past achievements when motivation is low", "Acknowledge one step forward you made today"],
    "5-medium": ["Set one specific goal for today and write it down", "Review your progress on a current project", "Break a big task into 3 small steps and do the first one"],
    "5-high": ["Tackle the one task you've been avoiding — start it now", "Send one message that moves a project forward", "Make a decision you've been sitting on"],
    "10-low": ["Journal on what achievement means to you right now", "Review your monthly goals and how you're tracking", "Write down 3 things you're proud of from the past month"],
    "10-medium": ["Do a 10-min focused work sprint on a goal", "Plan this week with achievement in mind — what must get done", "Write a specific goal with a deadline and first step"],
    "10-high": ["Do your hardest task first for 10 minutes", "Close one open loop — finish or decide on something pending", "Make a list of your wins this year — really look at how far you've come"],
    "20-low": ["Work slowly on a project that matters to you", "Journal about a goal you've been putting off and why", "Review and reflect on a past achievement and what made it possible"],
    "20-medium": ["Do a focused work session on a current goal", "Plan a project with milestones and deadlines", "Research what it takes to achieve something you're aiming for"],
    "20-high": ["Do a productive sprint on your most important goal", "Complete a task that's been on your list for too long", "Start something you've been afraid to start"],
    "45-low": ["Work steadily on a creative or personal project", "Journal deeply about what you really want to achieve", "Read about someone whose achievements inspire you"],
    "45-medium": ["Do a full work session on a meaningful project", "Complete a significant task or project milestone", "Plan the next 3 months of a goal you care about"],
    "45-high": ["Do a deep productive session — your best work for 45 minutes", "Finish something substantial", "Take a significant action toward a major goal"],
  },
  Responsibility: {
    "5-low": ["Write down one obligation you need to honour and the next step", "Acknowledge one commitment you've kept this week", "Do one small thing you said you'd do"],
    "5-medium": ["Respond to one message or email you've been deferring", "Pay one bill or admin task that's been pending", "Send a quick update to someone depending on you"],
    "5-high": ["Tackle your most important responsibility first — spend 5 min starting it", "Make one decision you've been responsible for but avoiding", "Clear your inbox of the most pressing items"],
    "10-low": ["Write a list of your current responsibilities and assess them", "Acknowledge what you're carrying and whether it's sustainable", "Journal about an area where you've been dropping the ball and why"],
    "10-medium": ["Do an admin sprint — clear 3 pending tasks", "Plan your week with your responsibilities mapped out first", "Check in with someone who's depending on you"],
    "10-high": ["Tackle your biggest outstanding responsibility", "Make a plan for something you've been avoiding", "Do a full inbox and task triage"],
    "20-low": ["Organise and tidy your physical space — a simple act of responsibility to yourself", "Review your commitments — are they realistic?", "Journal on what it means to you to be someone people can count on"],
    "20-medium": ["Do a full admin session — bills, emails, tasks", "Plan the next month with responsibilities mapped out", "Have an honest conversation about expectations with someone depending on you"],
    "20-high": ["Fully complete one major pending responsibility", "Design a system for managing your commitments reliably", "Take on a new responsibility you've been ready for but haven't stepped up to"],
    "45-low": ["Do a slow, thorough tidy or organise of your home or workspace", "Work through a pile of deferred admin", "Rest knowing you've honoured your responsibilities today"],
    "45-medium": ["Do a full life admin session — everything outstanding", "Plan a project or goal you're responsible for end-to-end", "Have a meeting or conversation that moves a shared responsibility forward"],
    "45-high": ["Lead a project session with full focus and accountability", "Complete a large and important task you've been responsible for", "Build a system that ensures you're reliably responsible going forward"],
  },
  Leadership: {
    "5-low": ["Write one specific thing you appreciate about your team", "Send a brief encouraging note to someone you lead or mentor", "Reflect on one leadership decision and what it taught you"],
    "5-medium": ["Share a resource, insight, or article with your team", "Give one clear piece of feedback to someone today", "Write down your leadership intention for this week"],
    "5-high": ["Make one clear decision that's been waiting on you", "Set a clear direction for a project and communicate it", "Ask your team one question: what do you need from me right now?"],
    "10-low": ["Read about a leader you admire — what can you take from them?", "Journal about your leadership style and where you want to grow", "Write down your team's strengths and how you're using them"],
    "10-medium": ["Plan a team meeting with a clear purpose and agenda", "Have a brief 1:1 check-in with someone you lead", "Identify one thing your team needs more of and plan to provide it"],
    "10-high": ["Make a difficult decision you've been putting off", "Give a piece of honest and constructive feedback", "Write a short vision or goals statement for your team"],
    "20-low": ["Read a leadership article or chapter", "Reflect on a recent leadership moment — what worked, what didn't", "Write individual strengths of each person you lead"],
    "20-medium": ["Plan a development conversation with a team member", "Redesign a meeting, process, or system that isn't working", "Do a 20-min deep-work session on a strategy or planning task"],
    "20-high": ["Run a productive and focussed team session", "Write a clear strategy for a project your team is working on", "Have a courageous leadership conversation you've been avoiding"],
    "45-low": ["Read a leadership book for a sustained session", "Watch a talk or interview on leadership and take notes", "Reflect and journal on the kind of leader you want to be"],
    "45-medium": ["Plan your team's next quarter", "Have a meaningful 1:1 with full attention and preparation", "Design a system or process that makes your team more effective"],
    "45-high": ["Run a full planning or strategy session", "Give a presentation, workshop, or lead a substantial discussion", "Do a full leadership self-review and set new development goals"],
  },
  "Helping Others": {
    "5-low": ["Text someone asking genuinely how they're doing", "Share a useful resource with someone who needs it", "Write a kind comment on something someone has shared"],
    "5-medium": ["Offer to help one person with something specific today", "Check in on someone who's been going through a hard time", "Share someone's work, fundraiser, or post to amplify them"],
    "5-high": ["Do one practical thing to help someone — proactively, without being asked", "Offer a skill or resource you have to someone who could use it", "Volunteer for something that came up in your community"],
    "10-low": ["Listen fully to someone — no advice, just presence", "Write a message of support to someone who's struggling", "Look up a local cause you could contribute to"],
    "10-medium": ["Help someone with a task they've mentioned — practical, specific", "Share knowledge on a topic someone in your network needs", "Have a supportive conversation with someone going through something difficult"],
    "10-high": ["Organise something helpful for a group — a resource, a document, an event", "Give someone specific and useful feedback they asked for", "Do a task that takes something off someone's plate"],
    "20-low": ["Sit with someone who needs company", "Write a thoughtful message to someone who has helped you — thank them properly", "Research a cause you care about and how to contribute"],
    "20-medium": ["Help someone with a project or problem for 20 focused minutes", "Run a short skill-share or tutorial for someone who asked", "Plan an act of service for someone this week"],
    "20-high": ["Organise a community or group initiative", "Teach someone a skill you have", "Do a practical, significant act of service"],
    "45-low": ["Spend time with someone who needs company — just be present", "Volunteer at a local community event", "Help someone with a slow, patient task"],
    "45-medium": ["Help with a meaningful project for a friend, family member, or cause", "Tutor, mentor, or coach someone for a session", "Organise something helpful for your community"],
    "45-high": ["Lead a volunteer session", "Run a workshop or skill-share for people who would benefit", "Plan and execute a significant act of help or service"],
  },
  Volunteering: {
    "5-low": ["Research one local volunteering opportunity", "Share a volunteering opportunity with your network", "Sign up to a mailing list for a cause you care about"],
    "5-medium": ["Reach out to a charity or organisation to ask how you can help", "Share your skills listing on a volunteer platform", "Donate to a cause — even a small amount with intention"],
    "5-high": ["Sign up to volunteer for one specific event or session", "Commit to a regular volunteering slot and put it in your calendar", "Recruit one friend to volunteer with you"],
    "10-low": ["Research an organisation you'd like to support", "Write a short message offering your skills to a cause", "Look up remote volunteering options you could do from home"],
    "10-medium": ["Do 10 minutes of online micro-volunteering — transcription, review, support", "Write a letter or email for a cause that needs it", "Help with admin or digital tasks for a non-profit remotely"],
    "10-high": ["Set up a recurring donation or volunteer commitment", "Plan and schedule your next 3 volunteering sessions", "Reach out to lead or organise a volunteering event"],
    "20-low": ["Browse and read about a cause you want to understand better", "Write about why volunteering matters to you", "Have a conversation with someone involved in community work"],
    "20-medium": ["Do a remote volunteering task — copy editing, design, research for an NGO", "Plan a fundraising activity", "Have a conversation with an organisation about how you can contribute long-term"],
    "20-high": ["Attend a volunteer orientation or onboarding", "Do a meaningful volunteer task — packing, delivery, tutoring", "Organise a community clean-up, collection, or event"],
    "45-low": ["Volunteer at a local charity shop or community centre", "Attend a volunteer community meeting", "Spend time with people who need company — elderly care, youth mentoring"],
    "45-medium": ["Do a full volunteering session at an organisation", "Run a community workshop or session", "Help organise a fundraiser or charity event"],
    "45-high": ["Lead a volunteering initiative", "Do a full active volunteering shift — physical, hands-on", "Run a workshop, training, or event for a cause you care about"],
  },
  Citizenship: {
    "5-low": ["Read one article about a local issue", "Follow a local news source or community account", "Write down one issue in your community you care about"],
    "5-medium": ["Share accurate information about a civic issue with your network", "Sign a petition for a cause you believe in", "Send a message of support to a local initiative"],
    "5-high": ["Write to your local representative about an issue that matters to you", "Share your vote or encourage others to use theirs", "Attend a local meeting or event — or find one to attend"],
    "10-low": ["Read about your local council, MP, or representative", "Learn about one issue affecting your community", "Watch a short news segment about your city or region"],
    "10-medium": ["Research candidates or parties before a local election", "Join a local community group or mailing list", "Write a letter or email to a local organisation about an issue"],
    "10-high": ["Attend a community meeting or town hall", "Organise or join a local campaign", "Volunteer for a voter registration or civic engagement drive"],
    "20-low": ["Read a long-form piece on a civic or political issue", "Listen to a local politics or community podcast", "Journal about your role as a citizen and what it means to you"],
    "20-medium": ["Attend a local council meeting", "Write a piece about a community issue — letter, post, article", "Research how to get more involved in local governance"],
    "20-high": ["Campaign for or organise around a cause", "Attend a political or community event", "Lead a conversation in your community about a shared issue"],
    "45-low": ["Attend a community event — market, meeting, celebration", "Read deeply about a civic issue that affects your area", "Have a thoughtful conversation about politics or society with someone you trust"],
    "45-medium": ["Volunteer for a local political or community campaign", "Attend a community planning meeting", "Organise a neighbourhood initiative"],
    "45-high": ["Lead a civic initiative or community project", "Attend a full political meeting and participate", "Run a community event, forum, or discussion"],
  },
  Environment: {
    "5-low": ["Pick up litter on your walk today", "Switch off lights and unplug devices you're not using", "Write down one environmental habit you want to build"],
    "5-medium": ["Research one sustainable swap you can make in your routine", "Share an environmental tip or resource with your network", "Make one purchase decision today with the environment in mind"],
    "5-high": ["Calculate your carbon footprint for one area of your life", "Sign up to an environmental organisation or mailing list", "Take one concrete action — cancel a subscription, switch a supplier"],
    "10-low": ["Read an article about an environmental issue you care about", "Research a local environmental group to connect with", "Journal about your relationship with the natural world"],
    "10-medium": ["Research and switch to a more sustainable product or supplier", "Take a walk and pick up litter intentionally", "Learn about your local ecosystem — what lives near you?"],
    "10-high": ["Audit your home for energy or waste inefficiencies and fix one", "Plan a meat-free week or a sustainability challenge", "Reach out to a local environmental organisation to get involved"],
    "20-low": ["Spend 20 minutes in nature — just observe", "Read about a conservation project or environmental success story", "Journal about what the natural world means to you"],
    "20-medium": ["Do a plastic or waste audit of your home", "Plan a week of more sustainable meals", "Research and join a local environmental group"],
    "20-high": ["Organise a community litter pick or environmental event", "Deep-clean and sort recyclables, compost, and waste systems at home", "Research and implement a significant environmental change"],
    "45-low": ["Take a long walk in nature with full attention", "Visit a local nature reserve or green space", "Sit outside and observe — birds, plants, sky"],
    "45-medium": ["Volunteer for a local conservation or clean-up project", "Plant something — seeds, herbs, a tree", "Redesign your shopping, eating, or energy habits for sustainability"],
    "45-high": ["Lead a community environmental project", "Do a full home sustainability audit and implement changes", "Attend an environmental workshop, event, or campaign"],
  },
  Faith: {
    "5-low": ["Say a short prayer or intention for the day", "Read one verse, passage, or teaching that speaks to you", "Light a candle and sit in a moment of acknowledgement"],
    "5-medium": ["Recite a prayer or mantra that is meaningful to you", "Write a short reflection on a spiritual teaching", "Share a moment of gratitude in whatever form feels right"],
    "5-high": ["Attend a short online or in-person religious or spiritual service", "Read an inspiring passage and write how it connects to your life", "Pray or meditate with a specific intention"],
    "10-low": ["Read from a sacred text or spiritual writing", "Sit in quiet and open prayer or contemplation", "Reflect on what your faith means to you today"],
    "10-medium": ["Write a faith journal entry — what are you believing, doubting, holding", "Listen to a religious teaching, sermon, or spiritual talk", "Practise a devotional ritual that is part of your tradition"],
    "10-high": ["Attend a short religious service or prayer group", "Study a passage or teaching in depth", "Have a conversation with someone about faith — honest and curious"],
    "20-low": ["Read a spiritual or religious text slowly and reflectively", "Sit in prayer or contemplative silence", "Visit a place of meaning — a church, temple, garden, space that connects you"],
    "20-medium": ["Write a longer faith journal entry", "Listen to a full religious talk or teaching", "Do a devotional practice with intention — prayer, study, reflection"],
    "20-high": ["Attend a faith community gathering", "Engage with a challenging spiritual question and sit with it", "Study a topic of theology, philosophy, or spiritual practice"],
    "45-low": ["Attend a full religious service", "Spend time in a place of spiritual significance", "Read and reflect at length from a sacred or spiritual text"],
    "45-medium": ["Participate in a faith community event", "Do a sustained devotional practice — reading, prayer, journaling", "Have a deep conversation about meaning, faith, and values"],
    "45-high": ["Lead or participate actively in a faith service or event", "Study a theological or spiritual topic in depth", "Do a retreat, workshop, or intensive spiritual practice"],
  },
  "Spiritual Growth": {
    "5-low": ["Sit quietly for 5 minutes with no goal", "Read one short spiritual or philosophical quote and reflect on it", "Take one slow conscious breath and check in with yourself"],
    "5-medium": ["Write 3 things that feel meaningful to you right now", "Journal one line about where you are spiritually today", "Do a 5-min guided meditation or visualisation"],
    "5-high": ["Write your core beliefs and whether your life reflects them", "Do a brief but intentional gratitude practice", "Set a spiritual intention for the day"],
    "10-low": ["Do a 10-min silent meditation or breath practice", "Read from a spiritual or philosophical text", "Sit in nature and be present without agenda"],
    "10-medium": ["Journal on a spiritual or existential question you're sitting with", "Listen to a talk or teaching from a teacher you respect", "Do a loving-kindness meditation"],
    "10-high": ["Do a focused breathwork or spiritual practice session", "Write about your spiritual values and whether you're living them", "Study a spiritual tradition you're curious about"],
    "20-low": ["Do a 20-min meditation or silent sit", "Walk in nature with full presence", "Rest and reflect — no input, just inner listening"],
    "20-medium": ["Journal deeply on a spiritual theme — purpose, meaning, connection", "Listen to a full spiritual talk or teaching", "Do a full breathwork or contemplative practice"],
    "20-high": ["Study a spiritual text or teaching with active engagement", "Have a deep conversation about meaning, death, purpose, or consciousness", "Do an intense meditation or contemplative practice"],
    "45-low": ["Sit in extended meditation or contemplative prayer", "Spend time in nature in full presence", "Read slowly and reflectively from a wisdom tradition"],
    "45-medium": ["Do a full spiritual practice session", "Attend a meditation class, kirtan, or contemplative gathering", "Journal extensively on your inner life and direction"],
    "45-high": ["Do a retreat-style session — full silence, meditation, journaling", "Study spiritual philosophy in depth", "Have a transformative conversation about the nature of self and meaning"],
  },
  Mindfulness: {
    "5-low": ["Do 5 slow, conscious breaths", "Notice 5 things you can see, 4 hear, 3 touch — grounding exercise", "Eat or drink something slowly and taste it fully"],
    "5-medium": ["Do a 5-min body scan meditation", "Walk for 5 minutes with full attention on your feet and breath", "Write one sentence about how you're feeling right now — no judgement"],
    "5-high": ["Do 5 minutes of focused breath observation with a timer", "Do a fast mindfulness reset — 60 seconds of full attention", "Write a stream-of-consciousness entry for 5 minutes"],
    "10-low": ["Do a 10-min guided mindfulness meditation", "Sit in silence and observe your thoughts without engaging them", "Do slow mindful stretching — full attention on each movement"],
    "10-medium": ["Do a 10-min body scan", "Take a mindful walk — no phone, full attention", "Journal on what's present in your mind and body right now"],
    "10-high": ["Do a focussed mindfulness practice — breath, body, sound", "Write about your emotional state with full honesty and curiosity", "Do a mindful movement session — yoga, tai chi, slow flow"],
    "20-low": ["Do a 20-min guided meditation", "Sit in nature and just observe", "Do a mindful rest — lie down and follow your breath"],
    "20-medium": ["Do a full mindfulness practice session", "Take a long mindful walk — single sense focus each 5 minutes", "Journal in a stream-of-consciousness style for 20 minutes"],
    "20-high": ["Do an extended breathwork session", "Practice mindful movement — yoga, qigong, slow running", "Write about a difficult emotion with curiosity and non-judgement"],
    "45-low": ["Do a full 45-min meditation or mindfulness class", "Spend time in nature with complete presence", "Do a long restorative yoga or body-awareness session"],
    "45-medium": ["Attend a live meditation class", "Do a full mindfulness journaling session — past, present, future", "Practice a mindful art — pottery, painting, calligraphy, with full attention"],
    "45-high": ["Do an intense meditation retreat session", "Do a full pranayama or breathwork intensive", "Have a mindful, deeply present conversation — no phone, full eye contact"],
  },
  Fun: {
    "5-low": ["Watch a funny video or clip that always makes you laugh", "Read a few comics or memes you enjoy", "Do a quick word game or brain teaser"],
    "5-medium": ["Play a quick mobile game you enjoy", "Send a funny message or meme to a friend", "Do a silly physical challenge — balance, juggling, anything daft"],
    "5-high": ["Do something spontaneous and slightly ridiculous", "Challenge someone to a quick game — table tennis, a coin flip series", "Make up a silly game with whoever is nearby"],
    "10-low": ["Watch a short comedy clip or stand-up segment", "Do a casual quick game — Wordle, crossword, puzzle", "Flick through a funny book or magazine"],
    "10-medium": ["Play a quick two-player game", "Do a mini trivia challenge with someone", "Watch a funny short film or animation"],
    "10-high": ["Do an active silly game — hopscotch, racing, anything physical and ridiculous", "Play a fast-paced card or word game competitively", "Go outside and do something active and fun — scooter, frisbee, ball"],
    "20-low": ["Watch an episode of a comfort comedy show", "Do a casual puzzle or creative game", "Play a slow board game with someone"],
    "20-medium": ["Play a proper board or card game", "Watch a funny film or series episode", "Go to an arcade, bowling alley, or mini golf"],
    "20-high": ["Play a sport or active game for fun", "Go to a trampoline park, climbing wall, or similar", "Have a dance party in your living room"],
    "45-low": ["Watch a full comedy film", "Do a slow jigsaw puzzle or colouring session", "Have a leisurely game afternoon"],
    "45-medium": ["Play a long board game or tabletop RPG", "Go bowling, mini golfing, or to an activity centre", "Have a games night with friends or family"],
    "45-high": ["Play a full sport game or match", "Go karting, climbing, or do an active experience", "Do a full active fun session — sport, movement, play"],
  },
  Adventure: {
    "5-low": ["Look up one place nearby you've never been", "Read about an adventure someone else is taking — a travel blog, a journal", "Write down 3 places or experiences you want to have in your life"],
    "5-medium": ["Walk a route you've never taken before", "Try one new food or drink you've never had", "Make a spontaneous decision — different lunch, different path home"],
    "5-high": ["Sign up for something you've been wanting to try", "Book a ticket to something exciting", "Say yes to something you'd normally hesitate on"],
    "10-low": ["Research a place you want to visit", "Read about an explorer or adventurer who inspires you", "Plan a small local adventure for this weekend"],
    "10-medium": ["Take a different route and explore your local area", "Try a new coffee shop, park, or neighbourhood", "Plan a day trip or mini adventure"],
    "10-high": ["Book a new activity you've never done", "Go somewhere unexpected for lunch or after work", "Start planning a real adventure — trip, challenge, experience"],
    "20-low": ["Browse travel photography or documentaries", "Plan a local adventure — a new area, a trail, a market", "Write a list of 20 adventures big and small you want to have"],
    "20-medium": ["Take a spontaneous trip to somewhere new nearby", "Explore a part of your city you've never been", "Do something active outside in a new location"],
    "20-high": ["Go for a run or cycle in a brand-new route", "Do a spontaneous outdoor activity — kayaking, hiking, climbing", "Start planning a major adventure — research, logistics, excitement"],
    "45-low": ["Take a slow explore of a new neighbourhood or town", "Visit a market, fair, or local event you've never attended", "Go for a long walk in unfamiliar terrain"],
    "45-medium": ["Go on a proper local adventure — hike, cycle, explore", "Visit somewhere new within reach by train or car", "Do an activity you've never tried — paddleboarding, archery, foraging"],
    "45-high": ["Do a challenging outdoor adventure — long hike, trail run, climb", "Go somewhere wild and unplanned", "Book and commit to a big adventure you've been putting off"],
  },
  Recreation: {
    "5-low": ["Stretch and move your body gently just for the feel of it", "Browse a hobby or interest you enjoy without a goal", "Sit outside and do nothing for 5 minutes"],
    "5-medium": ["Do a quick crossword, Sudoku, or puzzle", "Play 5 minutes of a hobby — guitar, knitting, drawing", "Take a short walk for no reason other than enjoyment"],
    "5-high": ["Do something active and physical just for fun", "Pick up a racket, ball, or instrument and play with it", "Get outside and move however feels good"],
    "10-low": ["Read a book purely for enjoyment", "Do a casual creative hobby — sketch, colour, knit", "Watch something you enjoy with no guilt"],
    "10-medium": ["Play a game you enjoy", "Go for a walk or short run", "Do a hobby for 10 minutes — guitar, painting, photography"],
    "10-high": ["Do a physical recreational activity — swim, cycle, skate", "Play a sport or game with energy", "Do a creative activity at pace — fast sketching, improvisation"],
    "20-low": ["Watch a film or show you've been meaning to enjoy", "Do a slow hobby session — reading, drawing, crafting", "Go for a gentle walk in a nice area"],
    "20-medium": ["Do a recreational sport or activity", "Play a game with friends or family", "Do a creative project for enjoyment"],
    "20-high": ["Play a proper sport or recreational activity", "Go for a long energetic walk, run, or cycle", "Do an active recreational experience — rock climbing, swimming, skating"],
    "45-low": ["Have a full leisure afternoon — films, reading, craft", "Go to a gallery, garden, or calm public space", "Do a slow hobby session with no pressure"],
    "45-medium": ["Attend a recreational class — dance, pottery, cookery", "Go somewhere enjoyable — a park, a market, a new area", "Do a longer recreational activity you love"],
    "45-high": ["Play a full game or sport session", "Do an active day out — hiking, cycling, kayaking", "Attend a recreational event or activity you've been wanting to try"],
  },
  Playfulness: {
    "5-low": ["Make a silly doodle or drawing", "Send a playful joke or meme to someone", "Do something in a ridiculous way — make your tea dramatically, narrate your actions"],
    "5-medium": ["Make up a game with whatever is around you", "Do impressions of something for no reason", "Play a quick word game — rhymes, wordplay, puns"],
    "5-high": ["Do something spontaneous and slightly ridiculous", "Challenge someone to an immediate silly competition", "Make up a dance or routine right now"],
    "10-low": ["Watch a silly or absurd video", "Read a funny book or comic", "Play a casual phone game"],
    "10-medium": ["Play a word game with someone — taboo, 20 questions, stories", "Make up a story together on the spot", "Do something creative with no rules — collage, doodle, build"],
    "10-high": ["Do an improv game — yes-and, character voices, made-up scenarios", "Have a dance battle or silly physical challenge", "Build something silly with whatever's to hand — lego, paper, anything"],
    "20-low": ["Watch a comedy special or silly film", "Do a casual creative play session — no goal", "Play a slow easy game for enjoyment"],
    "20-medium": ["Play a proper game — board game, card game, video game", "Do a creative improv session with a friend", "Build or make something purely for the joy of making"],
    "20-high": ["Do a physical playful activity — water fight, pillow fort, obstacle course", "Play a fast-paced competitive game", "Do something ridiculous and active — dance challenge, charades, outdoor game"],
    "45-low": ["Watch a full comedy film", "Do a full art or creative session with no outcome in mind", "Have a slow games afternoon"],
    "45-medium": ["Host a games night", "Do a full creative play session — make things, try things, break rules", "Go somewhere playful — arcade, adventure park, escape room"],
    "45-high": ["Do a full active playful adventure — theme park, sports, obstacle race", "Run an improv or creative workshop", "Plan and execute a full silly, spontaneous adventure"],
  },
  Compassion: {
    "5-low": ["Think of someone who is struggling and send them a kind thought", "Write a short message to someone you know is having a hard time", "Donate a small amount to a cause that helps people in need"],
    "5-medium": ["Reach out to check in on someone who might need it", "Write a kind message to someone who has been going through difficulty", "Share a resource that might help someone you care about"],
    "5-high": ["Do one concrete act of kindness for someone who needs it today", "Offer help to someone without waiting to be asked", "Speak up for someone or something when it feels uncomfortable"],
    "10-low": ["Read about a cause or population you want to understand better", "Reflect on someone's situation with genuine empathy — write it out", "Listen to someone without advice or judgement"],
    "10-medium": ["Have a conversation where your only goal is to understand", "Do something practical for someone who is overwhelmed", "Write a letter of support to someone going through a hard time"],
    "10-high": ["Volunteer your time or skills for someone in need", "Organise something helpful for a person or group", "Have a hard, caring conversation with someone who needs honesty and warmth"],
    "20-low": ["Read a book or story that builds empathy for others' experience", "Volunteer for a listening or support service", "Journal about compassion — where you feel it, where you block it"],
    "20-medium": ["Spend time with someone who is lonely or struggling", "Do a significant act of practical support", "Run a brief support or mentoring session with someone"],
    "20-high": ["Lead a compassion initiative — organise help, resources, or support", "Have a deep and honest supportive conversation", "Take action on an injustice you've been aware of"],
    "45-low": ["Volunteer with an organisation that supports vulnerable people", "Spend meaningful time with someone who needs presence", "Watch a documentary that deepens your understanding of human suffering and strength"],
    "45-medium": ["Do a full volunteering session with a welfare or support organisation", "Mentor or support someone through a specific difficulty", "Plan and execute a meaningful act of service or advocacy"],
    "45-high": ["Lead a support initiative or campaign", "Do a full advocacy or community support session", "Have a transformative conversation that helps someone through something difficult"],
  },
  Honesty: {
    "5-low": ["Write one thing you haven't been fully honest with yourself about", "Notice one small way you've been avoiding truth today", "Read a quote about honesty or integrity that resonates"],
    "5-medium": ["Write one thing you need to say to someone that you've been holding back", "Have one small honest moment — admit uncertainty, acknowledge a mistake", "Journal briefly on where honesty is hard for you right now"],
    "5-high": ["Have one honest conversation you've been avoiding", "Admit something you got wrong to someone affected", "Set a record straight on something you've let slide"],
    "10-low": ["Journal on your relationship with honesty — where is it easy, where is it hard?", "Reflect on a time you were honest and what it cost and gave you", "Read or listen to something about integrity and courage"],
    "10-medium": ["Write a draft of an honest message you need to send", "Have an honest check-in with yourself about your values and actions", "Acknowledge a mistake to yourself and identify the repair"],
    "10-high": ["Send the honest message you've been holding back", "Have a direct, truthful conversation about something that matters", "Make a decision based on your values, not on what's comfortable"],
    "20-low": ["Journal extensively on your inner truth — what you really think, feel, want", "Read about honesty, courage, or integrity in depth", "Reflect on your patterns of avoidance or self-deception"],
    "20-medium": ["Have an honest conversation about something real with someone you trust", "Write a letter to yourself — fully truthful, no performance", "Review a decision or situation with complete honesty and note what you'd do differently"],
    "20-high": ["Have a courageous conversation you've been postponing", "Take an action that reflects your values even when it's uncomfortable", "Do a full honesty audit of your life — where are you performing? where are you real?"],
    "45-low": ["Read a book on integrity, authenticity, or moral courage", "Journal deeply on who you really are beneath the roles you play", "Spend time with someone with whom you can be completely yourself"],
    "45-medium": ["Have a long, honest conversation about your relationship, work, or life direction", "Write a full honest self-assessment — strengths, blindspots, growth edges", "Do a values review — what do you say you believe vs how do you actually live?"],
    "45-high": ["Have a transformative honest conversation", "Make a significant decision based entirely on your deepest values", "Write and commit to a personal integrity statement"],
  },
  Courage: {
    "5-low": ["Write down one thing you're afraid of and why", "Read about someone who acted courageously in the face of fear", "Acknowledge one thing you've been avoiding and name it honestly"],
    "5-medium": ["Make one decision you've been putting off out of fear", "Say yes to something slightly uncomfortable", "Do the first step of something scary — send the first message, write the first line"],
    "5-high": ["Do the scary thing — apply, send it, say it, show up", "Have one honest conversation you've been avoiding", "Take a risk you've been rationalising your way out of"],
    "10-low": ["Journal on where fear is running your life right now", "Read or listen to something about courage and fear", "Reflect on a time you were brave — what made it possible?"],
    "10-medium": ["Write a letter to your fear — what is it protecting? what is it costing?", "Identify the one thing fear is most stopping you from and take one small step", "Share something honest or vulnerable with one person"],
    "10-high": ["Do something physically challenging — cold shower, hard workout, something outside your comfort zone", "Have a courageous conversation with someone", "Publicly commit to something you've been afraid to say out loud"],
    "20-low": ["Journal deeply on your relationship with fear and courage", "Read about a person who acted bravely in a situation you relate to", "Reflect on your life: where are you playing small?"],
    "20-medium": ["Write about the life you'd live if you weren't afraid and compare it to now", "Take a meaningful step toward something you've been afraid to pursue", "Have an honest conversation about something that's been left unsaid"],
    "20-high": ["Do something courageous that costs you something real", "Pursue something publicly that you've been keeping private out of fear", "Make a significant decision based on courage rather than comfort"],
    "45-low": ["Spend time reflecting on what courage means in your life right now", "Read a book about courage, risk, or someone who lived fully", "Journal on your biggest unlived dream and what fear stands between you and it"],
    "45-medium": ["Take a significant step toward something you've been afraid of", "Have a long and courageous conversation", "Attend something that challenges you — a class, a meeting, an event you've avoided"],
    "45-high": ["Do the thing. The big one you've been waiting for the right time to do", "Have a full courageous conversation about something life-changing", "Commit fully and publicly to something that requires real courage"],
  },
  Gratitude: {
    "5-low": ["Write 3 specific things you're grateful for right now", "Send a brief thank-you message to someone who helped you recently", "Look at something around you and notice why you're glad it exists"],
    "5-medium": ["Write a proper thank-you note to someone — not generic, specific", "Share appreciation for someone out loud today", "Write what you're grateful for about your body, your home, your life right now"],
    "5-high": ["Call or message someone to tell them specifically what they mean to you", "Write a gratitude entry that goes beyond the obvious — dig deeper", "Do a gratitude practice and share it with someone else"],
    "10-low": ["Write a full gratitude journal entry — people, moments, things, your own qualities", "Sit quietly and appreciate something you usually take for granted", "Read or listen to something that reminds you of abundance"],
    "10-medium": ["Write a proper letter of gratitude to someone who changed your life", "Make a list of 20 things you're grateful for — keep going past the easy ones", "Have a conversation where you express genuine appreciation"],
    "10-high": ["Write and send a gratitude letter to someone significant", "Start a gratitude practice with structure — daily, specific, handwritten", "Do a gratitude inventory: health, relationships, opportunities, beauty around you"],
    "20-low": ["Write an extended gratitude journal — go deep, be specific", "Sit in a beautiful or meaningful place and appreciate it fully", "Look through old photos and feel genuine thankfulness for what you've had"],
    "20-medium": ["Write and send multiple gratitude messages to people who've shaped you", "Do a life review through the lens of gratitude — what has been given to you", "Create a gratitude ritual and commit to it for 30 days"],
    "20-high": ["Write a long letter of gratitude to yourself — for getting here, for surviving, for growing", "Have a conversation where the only purpose is to express appreciation", "Plan a meaningful gesture of thanks for someone who deserves it"],
    "45-low": ["Spend time in a place that fills you with gratitude — nature, a meaningful space", "Write extensively about the people who have shaped your life with thankfulness", "Rest and allow appreciation — for your body, your breath, this moment"],
    "45-medium": ["Cook a meal for someone as an act of gratitude", "Visit someone you're grateful for — just to be with them", "Do a full gratitude journaling session across all areas of your life"],
    "45-high": ["Plan and execute a meaningful act of gratitude — an event, a gift, an experience", "Have a deep conversation with someone about what they mean to you", "Create something as an act of gratitude — write, make, build, dedicate"],
  },
  Kindness: {
    "5-low": ["Send a warm message to someone who might need it", "Leave a genuine compliment on something someone has created", "Do one small kind thing for yourself — make a nice drink, rest, be gentle"],
    "5-medium": ["Do one spontaneous act of kindness for a stranger", "Write a kind note and leave it somewhere it will be found", "Share something helpful or uplifting with your network"],
    "5-high": ["Do something kind and slightly effortful for someone — buy a coffee, hold a door, help carry something", "Reach out to someone you know is struggling and offer specific help", "Do something kind for yourself that you've been denying yourself"],
    "10-low": ["Write a list of people you want to be kinder to and how", "Reflect on a time you received kindness and what it meant", "Do something gentle and caring for your own body or mind"],
    "10-medium": ["Send a proper message of kindness to someone you appreciate", "Do a kind task for a neighbour, colleague, or stranger", "Write a gratitude message that is specifically about someone's kindness to you"],
    "10-high": ["Organise something kind for someone going through a hard time", "Make or buy something thoughtful for someone who needs a boost", "Speak up kindly for someone in a situation where it costs you something"],
    "20-low": ["Sit with someone who needs company — that is kindness", "Write kind letters to people you love", "Do a full self-compassion practice — speak to yourself as you would a dear friend"],
    "20-medium": ["Do a random act of kindness in your community", "Cook or bring food to someone who needs it", "Plan a week of intentional kindness — one act per day, written and committed to"],
    "20-high": ["Organise a community kindness initiative", "Do something significantly kind for a person or group — practical, meaningful", "Have a conversation where the only goal is to make someone feel genuinely seen"],
    "45-low": ["Volunteer for a service that needs kind presence", "Spend time with someone who needs care — elderly, ill, lonely", "Create something as an act of kindness — make, cook, build for someone else"],
    "45-medium": ["Organise a kindness event or initiative in your community", "Cook a full meal for someone and deliver it", "Spend meaningful, attentive time with someone who needs it"],
    "45-high": ["Lead a kindness initiative or community project", "Do a full day of intentional, active, effortful kindness", "Create something significant for someone — an experience, a piece of work, a gift — as a pure act of love"],
  },
};

const TIME_OPTIONS = [5, 10, 20, 45];

export function generate(value: string, minutes: number, energy: string): Suggestion[] {
  const closestTime = TIME_OPTIONS.reduce((prev, curr) =>
    Math.abs(curr - minutes) < Math.abs(prev - minutes) ? curr : prev
  );

  const energyOrder = ["high", "medium", "low"];
  const startIdx = energyOrder.indexOf(energy);
  const levelsToTry = startIdx >= 0 ? energyOrder.slice(startIdx) : energyOrder;

  for (const e of levelsToTry) {
    const texts = ACTIVITIES[value]?.[`${closestTime}-${e}`] ?? [];
    if (texts.length > 0) {
      return texts.map((text) => ({
        text,
        minutes: closestTime,
        energy: e as Suggestion["energy"],
      }));
    }
  }

  return [
    { text: "Take one small step toward this value", minutes: closestTime, energy: "low" },
    { text: "Spend a few focused minutes on what matters here", minutes: closestTime, energy: "low" },
  ];
}

export function resize(text: string): string {
  const lower = text.toLowerCase();
  const RULES: [RegExp, string][] = [
    [/clean (the |your )?(entire |whole )?(apartment|house|home)/, "Clean one shelf"],
    [/go to the gym.*/, "Put on your gym clothes"],
    [/(do a |a )?\d+-?minute (home )?workout/, "Stretch for 2 minutes"],
    [/cook dinner.*/, "Make a simple snack together"],
    [/read \d+ pages.*/, "Read one page"],
    [/run .*/, "Walk for 5 minutes"],
    [/(20|30|45)-?\s?minute walk/, "Walk to the end of the street"],
    [/walk .*/, "Step outside for 2 minutes"],
    [/complete one lesson.*/, "Watch the first 5 minutes of a lesson"],
  ];
  for (const [re, smaller] of RULES) {
    if (re.test(lower)) return smaller;
  }
  return "Do just the first 2 minutes of this";
}

export function difficultyMeta(d: string): { color: string; bg: string } {
  const map: Record<string, { color: string; bg: string }> = {
    Easy: { color: "#5E8C3C", bg: "#E8EFD8" },
    Medium: { color: "var(--accent-deep)", bg: "var(--accent-soft)" },
    Hard: { color: "#C0512E", bg: "#F4E5DD" },
  };
  return map[d] || { color: "var(--fg-secondary)", bg: "var(--bg-sunken)" };
}
